language: csharp
mono: none
# Need explicit dotnet version otherwise OSX fails to download/install dotnet
# Test runner requires dotnet core 2.1 sdk
dotnet: 3.1.101

matrix:
  include:
    - os: osx
      osx_image: xcode11
    - os: linux
      dist: bionic
sudo: required
services:
  - docker

# At least one script line is required:
# https://docs.travis-ci.com/user/languages/csharp/#net-core
script:
  - dotnet restore
  - dotnet build
  - dotnet test --verbosity normal tests

after_success:
  - ./scripts/qemu_arm64.sh