language: csharp
mono: none
# Need explicit dotnet version otherwise OSX fails to download/install dotnet
# Test runner requires dotnet core 2.1 sdk
dotnet: 2.2.207

jobs:
  include:
    # No matter what, can't get it to use Ubuntu Bionic (18.04) instead of Xenial (16.04)
    #- dist: bionic
    - os: osx
sudo: required
services:
  - docker

# At least one script line is required:
# https://docs.travis-ci.com/user/languages/csharp/#net-core
script:
  - dotnet restore
  - dotnet build
  - dotnet test --filter "platform!=windows" --verbosity normal tests

after_success:
  - ./scripts/qemu_arm64.sh