name: publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2019
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
    - name: Checkout nng.NET
      uses: actions/checkout@v2
    - name: Package
      run: |
        ./scripts/nupkg.ps1 -Version ${{ github.event.release.tag_name }} -CertBase64 ${{ secrets.CODE_SIGN_CERT_BASE64 }} -NugetApiKey ${{ secrets.NUGET_API_KEY }}
        